### ISSUE TITLE
Crear modelos User y Wallet

### ISSUE THREAD

**Issue by canales126497** [ilukep00/vvs_crypto_wallet#22]
Refers to [#21]

A la larga nos va a hacer falta un modelo User que almacene todas las Wallets de ese usuario; por tanto deberiamos implementar los modelos User y Wallet.

**Comment by ashzud** [comment]
Yo también necesito los modelos Coin y Wallet para [#9]

**Comment by canales126497** [comment]
Vale apuntado, creo una rama para la creación de los tres modelos

**Comment by canales126497** [comment]
Estaría bien que incluyesemos la funcionalidad para calcular el precio de las monedas dentro del propio modelo de Coin para poder por ejemplo calcular el beneficio que ha proporcionado cada tipo de moneda
